# we might be able to use the kubo-deployment cloud-config ops files if they merge them...
- type: replace
  path: /vm_extensions/-
  value:
    name: cfcr-master-network-properties
    cloud_properties:
      target_pool: ((cfcr_master_target_pool))
      tags:
      - ((cfcr_master_target_pool))

- type: replace
  path: /vm_extensions/name=cfcr-master-iam-properties?/cloud_properties/
  value:
    service_account: ((service_account_master))

- type: replace
  path: /vm_extensions/name=cfcr-master-iam-properties?/cloud_properties/
  value:
    service_account: ((service_account_master))
